---

yaml-files:
  - '*.yaml'
  - '*.yml'

ignore:
  - '**/.deploy/charts/*/templates'

rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments: enable
  comments-indentation: enable
  document-end: disable
  document-start: disable
  empty-lines: enable
  empty-values: disable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: disable
  octal-values: enable
  quoted-strings: disable
  trailing-spaces: enable
  truthy: disable
