name: FullWorkflow-Deploy-a

on:
  push:
    branches:
      - main
    paths:
      - 'model/a/**'

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  style:
    uses: ./.github/workflows/style.yml
  tests_a:
    uses: ./.github/workflows/tests.yml
    with:
      src_path: "model/a"
  python_style_a:
    uses: ./.github/workflows/python_style.yml
    with:
      src_path: "model/a"
  release:
    needs: [style, tests_a, python_style_a]
    uses: ./.github/workflows/release.yaml
