name: FullWorkflow-Deploy-b

on:
  push:
    branches:
      - main
    paths:
      - 'model/b/**'

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  style:
    uses: ./.github/workflows/style.yml
  tests_b:
    uses: ./.github/workflows/tests.yml
    with:
      src_path: "model/b"
  python_style_b:
    uses: ./.github/workflows/python_style.yml
    with:
      src_path: "model/b"
  release:
    needs: [style, tests_b, python_style_b]
    uses: ./.github/workflows/release.yaml
